import type { Report } from '@/lib/store';

export function formatFilename(label: string, extension: 'json' | 'md', date = new Date()): string {
  const safeLabel = label
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'export';
  const timestamp = date.toISOString().replace(/:/g, '-').replace(/\.\d+Z$/, 'Z');

  return `${safeLabel}-${timestamp}.${extension}`;
}

export function createExportEnvelope(label: string, data: unknown, exportedBy: string, exportedAt = new Date().toISOString()) {
  return {
    meta: {
      label,
      exportedBy,
      exportedAt,
      recordCount: Array.isArray(data) ? data.length : undefined,
    },
    data,
  };
}

export function createAllDataSnapshot(data: Record<string, unknown>, exportedBy: string, exportedAt = new Date().toISOString()) {
  return {
    meta: {
      exportedBy,
      exportedAt,
      collectionCount: Object.keys(data).length,
    },
    data,
  };
}

export function formatReportMarkdown(report: Report): string {
  const metrics = Object.entries(report.data)
    .map(([key, value]) => `- ${humanizeKey(key)}: ${formatMetricValue(value)}`)
    .join('\n');

  return [
    `# ${report.title}`,
    '',
    `- Type: ${report.type}`,
    `- Generated by: ${report.generatedBy}`,
    `- Generated at: ${new Date(report.generatedAt).toLocaleString()}`,
    '',
    '## Metrics',
    '',
    metrics || '- No metrics available.',
    '',
  ].join('\n');
}

export function downloadJsonFile(label: string, payload: unknown, date = new Date()): string {
  const filename = formatFilename(label, 'json', date);
  downloadTextFile(filename, JSON.stringify(payload, null, 2), 'application/json;charset=utf-8');
  return filename;
}

export function downloadReportMarkdown(report: Report): string {
  const filename = formatFilename(report.title, 'md', new Date(report.generatedAt));
  downloadTextFile(filename, formatReportMarkdown(report), 'text/markdown;charset=utf-8');
  return filename;
}

function downloadTextFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function humanizeKey(value: string): string {
  const withSpaces = value.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').trim();
  return withSpaces.charAt(0).toUpperCase() + withSpaces.slice(1);
}

function formatMetricValue(value: unknown): string {
  if (Array.isArray(value) || (value !== null && typeof value === 'object')) {
    return JSON.stringify(value);
  }

  return String(value);
}
